# based on https://github.com/marketplace/actions/build-and-push-docker-images
name: Build All Components

on: 
  schedule: 
    # build once a month
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: [self-hosted, linux, x64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # https://github.com/stefanzweifel/git-auto-commit-action

      -
        name: Build and push
        id: docker_build
        run: |
          bash build_all.sh